### ISSUE TITLE
Setup more than one channel at once

### ISSUE THREAD

**Issue by riasuh** [Milozz01/ssb#7]
`chan_list = [11,12]    # add as many channels as you want!
                       # you can tuples instead i.e.:
                       #   chan_list = (11,12)
GPIO.setup(chan_list, GPIO.OUT)`

**Comment by riasuh** [comment]
`
chan_list = [11,12]                             # also works with tuples
GPIO.output(chan_list, GPIO.LOW)                # sets all to GPIO.LOW
GPIO.output(chan_list, (GPIO.HIGH, GPIO.LOW))   # sets first HIGH and second LOW`

**Comment by Milozz01** [comment]
[](https://sourceforge.net/p/raspberry-gpio-python/wiki/BasicUsage/)

**Comment by riasuh** [comment]
[https://sourceforge.net/p/raspberry-gpio-python/wiki/BasicUsage/](https://sourceforge.net/p/raspberry-gpio-python/wiki/BasicUsage/)
